/*
 * Cayley API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// JsonQuad struct for JsonQuad
type JsonQuad struct {
	Subject string `json:"subject,omitempty"`
	Predicate string `json:"predicate,omitempty"`
	Object string `json:"object,omitempty"`
	Label string `json:"label,omitempty"`
}
