/*
 * Cayley API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// Error struct for Error
type Error struct {
	// error message
	Error string `json:"error,omitempty"`
}
