/*
 * Cayley API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// InlineResponse200 struct for InlineResponse200
type InlineResponse200 struct {
	// unique name of the format
	Id string `json:"id,omitempty"`
	// format is supported for loading quads
	Read bool `json:"read,omitempty"`
	// format is supported for exporting quads
	Write bool `json:"write,omitempty"`
	// format can be used to describe nodes
	Nodes bool `json:"nodes,omitempty"`
	// typical file extensions for this format
	Ext []string `json:"ext,omitempty"`
	// typical content types for this format
	Mime []string `json:"mime,omitempty"`
	// format uses binary encoding
	Binary bool `json:"binary,omitempty"`
}
