/*
 * Cayley API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse2001 struct for InlineResponse2001
type InlineResponse2001 struct {
	// legacy success message
	Result string `json:"result,omitempty"`
	// number of quads received
	Count int32 `json:"count,omitempty"`
}
