build:
  - platform: src
  - platform: linux
    arch:
      - amd64
      - arm64
      - arm
      - "386"
  - platform: darwin
    arch:
      - "386"
      - amd64
  - platform: windows
    arch:
      - "386"
      - amd64
ld:
  versionPath: "main.Version"
  buildDatePath: "main.BuildDate"
mains:
  - "./cmd/cayley"
  - "./cmd/cayleyupgrade"
include:
  - README.md
  - LICENSE
  - AUTHORS
  - CONTRIBUTORS
  - docs
  - static
  - templates
  - cayley.cfg.example
  - data
outputDir: "$GOPATH/bin"
