FROM sugarush/cayley

LABEL maintainer "napalmbrain (psev)"
LABEL email "github@napalmbrain.sugarush.io"
LABEL github "github.com/sugarush"

RUN mkdir /data
VOLUME [ "/data" ]

COPY data/30kmoviedata.nq.gz /tmp/30kmoviedata.nq.gz

RUN echo '{"database":"bolt","db_path":"/data/cayley","read_only":false}' > /data/cayley.cfg &&
    cayley init -db bolt -dbpath /data/cayley -quads /tmp/30kmoviedata.nq.gz && \
    rm /tmp/30kmoviedata.nq.gz

CMD [ "http", "-config", "/data/cayley.cfg", "-host", "0.0.0.0", "-port", "64210" ]
