// Code generated by protoc-gen-gogo.
// source: primitive.proto
// DO NOT EDIT!

/*
	Package graph is a generated protocol buffer package.

	It is generated from these files:
		primitive.proto

	It has these top-level messages:
		Primitive
*/
package graph

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/golang/protobuf/ptypes/timestamp"

import time "time"

import github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ValueType int32

const (
	ValueType_IRI       ValueType = 0
	ValueType_STRING    ValueType = 1
	ValueType_BNODE     ValueType = 2
	ValueType_TYPED_STR ValueType = 3
	ValueType_LANG_STR  ValueType = 4
	ValueType_INT       ValueType = 5
	ValueType_FLOAT     ValueType = 6
	ValueType_BOOL      ValueType = 7
	ValueType_TIMESTAMP ValueType = 8
)

var ValueType_name = map[int32]string{
	0: "IRI",
	1: "STRING",
	2: "BNODE",
	3: "TYPED_STR",
	4: "LANG_STR",
	5: "INT",
	6: "FLOAT",
	7: "BOOL",
	8: "TIMESTAMP",
}
var ValueType_value = map[string]int32{
	"IRI":       0,
	"STRING":    1,
	"BNODE":     2,
	"TYPED_STR": 3,
	"LANG_STR":  4,
	"INT":       5,
	"FLOAT":     6,
	"BOOL":      7,
	"TIMESTAMP": 8,
}

func (x ValueType) String() string {
	return proto.EnumName(ValueType_name, int32(x))
}
func (ValueType) EnumDescriptor() ([]byte, []int) { return fileDescriptorPrimitive, []int{0} }

type Primitive struct {
	ID        uint64     `protobuf:"varint,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	Subject   uint64     `protobuf:"varint,2,opt,name=Subject,json=subject,proto3" json:"Subject,omitempty"`
	Predicate uint64     `protobuf:"varint,3,opt,name=Predicate,json=predicate,proto3" json:"Predicate,omitempty"`
	Object    uint64     `protobuf:"varint,4,opt,name=Object,json=object,proto3" json:"Object,omitempty"`
	Label     uint64     `protobuf:"varint,5,opt,name=Label,json=label,proto3" json:"Label,omitempty"`
	SameAs    uint64     `protobuf:"varint,6,opt,name=SameAs,json=sameAs,proto3" json:"SameAs,omitempty"`
	Replaces  uint64     `protobuf:"varint,7,opt,name=Replaces,json=replaces,proto3" json:"Replaces,omitempty"`
	Timestamp *time.Time `protobuf:"bytes,8,opt,name=Timestamp,json=timestamp,stdtime" json:"Timestamp,omitempty"`
	ValueType ValueType  `protobuf:"varint,9,opt,name=ValueType,json=valueType,proto3,enum=graph.ValueType" json:"ValueType,omitempty"`
	Value     []byte     `protobuf:"bytes,10,opt,name=Value,json=value,proto3" json:"Value,omitempty"`
}

func (m *Primitive) Reset()                    { *m = Primitive{} }
func (m *Primitive) String() string            { return proto.CompactTextString(m) }
func (*Primitive) ProtoMessage()               {}
func (*Primitive) Descriptor() ([]byte, []int) { return fileDescriptorPrimitive, []int{0} }

func (m *Primitive) GetTimestamp() *time.Time {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func init() {
	proto.RegisterType((*Primitive)(nil), "graph.Primitive")
	proto.RegisterEnum("graph.ValueType", ValueType_name, ValueType_value)
}
func (m *Primitive) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Primitive) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintPrimitive(dAtA, i, uint64(m.ID))
	}
	if m.Subject != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintPrimitive(dAtA, i, uint64(m.Subject))
	}
	if m.Predicate != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintPrimitive(dAtA, i, uint64(m.Predicate))
	}
	if m.Object != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintPrimitive(dAtA, i, uint64(m.Object))
	}
	if m.Label != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintPrimitive(dAtA, i, uint64(m.Label))
	}
	if m.SameAs != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintPrimitive(dAtA, i, uint64(m.SameAs))
	}
	if m.Replaces != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintPrimitive(dAtA, i, uint64(m.Replaces))
	}
	if m.Timestamp != nil {
		dAtA[i] = 0x42
		i++
		i = encodeVarintPrimitive(dAtA, i, uint64(github_com_gogo_protobuf_types.SizeOfStdTime(*m.Timestamp)))
		n1, err := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.Timestamp, dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.ValueType != 0 {
		dAtA[i] = 0x48
		i++
		i = encodeVarintPrimitive(dAtA, i, uint64(m.ValueType))
	}
	if len(m.Value) > 0 {
		dAtA[i] = 0x52
		i++
		i = encodeVarintPrimitive(dAtA, i, uint64(len(m.Value)))
		i += copy(dAtA[i:], m.Value)
	}
	return i, nil
}

func encodeFixed64Primitive(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Primitive(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintPrimitive(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Primitive) Size() (n int) {
	var l int
	_ = l
	if m.ID != 0 {
		n += 1 + sovPrimitive(uint64(m.ID))
	}
	if m.Subject != 0 {
		n += 1 + sovPrimitive(uint64(m.Subject))
	}
	if m.Predicate != 0 {
		n += 1 + sovPrimitive(uint64(m.Predicate))
	}
	if m.Object != 0 {
		n += 1 + sovPrimitive(uint64(m.Object))
	}
	if m.Label != 0 {
		n += 1 + sovPrimitive(uint64(m.Label))
	}
	if m.SameAs != 0 {
		n += 1 + sovPrimitive(uint64(m.SameAs))
	}
	if m.Replaces != 0 {
		n += 1 + sovPrimitive(uint64(m.Replaces))
	}
	if m.Timestamp != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.Timestamp)
		n += 1 + l + sovPrimitive(uint64(l))
	}
	if m.ValueType != 0 {
		n += 1 + sovPrimitive(uint64(m.ValueType))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovPrimitive(uint64(l))
	}
	return n
}

func sovPrimitive(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozPrimitive(x uint64) (n int) {
	return sovPrimitive(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Primitive) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPrimitive
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Primitive: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Primitive: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPrimitive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Subject", wireType)
			}
			m.Subject = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPrimitive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Subject |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Predicate", wireType)
			}
			m.Predicate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPrimitive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Predicate |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Object", wireType)
			}
			m.Object = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPrimitive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Object |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Label", wireType)
			}
			m.Label = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPrimitive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Label |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SameAs", wireType)
			}
			m.SameAs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPrimitive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SameAs |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Replaces", wireType)
			}
			m.Replaces = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPrimitive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Replaces |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPrimitive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPrimitive
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Timestamp == nil {
				m.Timestamp = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.Timestamp, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValueType", wireType)
			}
			m.ValueType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPrimitive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValueType |= (ValueType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPrimitive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPrimitive
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = append(m.Value[:0], dAtA[iNdEx:postIndex]...)
			if m.Value == nil {
				m.Value = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPrimitive(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPrimitive
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPrimitive(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPrimitive
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPrimitive
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPrimitive
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthPrimitive
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowPrimitive
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipPrimitive(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthPrimitive = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPrimitive   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("primitive.proto", fileDescriptorPrimitive) }

var fileDescriptorPrimitive = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x90, 0xdb, 0x8a, 0xd3, 0x40,
	0x18, 0xc7, 0x77, 0xd2, 0x9c, 0xe6, 0x73, 0x5d, 0x87, 0x41, 0x64, 0x28, 0xd2, 0x2d, 0x5e, 0x15,
	0xc1, 0x2c, 0xac, 0xf7, 0x42, 0x4b, 0xeb, 0x12, 0xe8, 0x36, 0x65, 0x32, 0x08, 0x5e, 0x49, 0x52,
	0xc7, 0x6c, 0x24, 0x61, 0x42, 0x0e, 0x0b, 0xbe, 0xc5, 0xbe, 0x8f, 0x2f, 0xe0, 0xa5, 0x6f, 0xa0,
	0xd4, 0x17, 0x91, 0x7c, 0x31, 0x75, 0xef, 0xbe, 0xff, 0xe1, 0x97, 0xe4, 0x1f, 0x78, 0x56, 0xd5,
	0x79, 0x99, 0xb7, 0xf9, 0xbd, 0x0e, 0xaa, 0xda, 0xb4, 0x86, 0x3b, 0x59, 0x9d, 0x54, 0x77, 0xd3,
	0x37, 0x59, 0xde, 0xde, 0x75, 0x69, 0x70, 0x30, 0xe5, 0x55, 0x66, 0x32, 0x73, 0x85, 0x69, 0xda,
	0x7d, 0x41, 0x85, 0x02, 0xaf, 0x81, 0x9a, 0x5e, 0x66, 0xc6, 0x64, 0x85, 0xfe, 0xdf, 0x6a, 0xf3,
	0x52, 0x37, 0x6d, 0x52, 0x56, 0x43, 0xe1, 0xd5, 0x77, 0x0b, 0xe8, 0x7e, 0x7c, 0x15, 0xbf, 0x00,
	0x2b, 0x5c, 0x0b, 0x32, 0x27, 0x0b, 0x5b, 0x5a, 0xf9, 0x9a, 0x0b, 0xf0, 0xe2, 0x2e, 0xfd, 0xaa,
	0x0f, 0xad, 0xb0, 0xd0, 0xf4, 0x9a, 0x41, 0xf2, 0x97, 0x3d, 0xa6, 0x3f, 0xe7, 0x87, 0xa4, 0xd5,
	0x62, 0x82, 0x19, 0xad, 0x46, 0x83, 0xbf, 0x00, 0x37, 0x1a, 0x30, 0x1b, 0x23, 0xd7, 0x0c, 0xd4,
	0x73, 0x70, 0xb6, 0x49, 0xaa, 0x0b, 0xe1, 0xa0, 0xed, 0x14, 0xbd, 0xe8, 0xdb, 0x71, 0x52, 0xea,
	0x65, 0x23, 0xdc, 0xa1, 0xdd, 0xa0, 0xe2, 0x53, 0xf0, 0xa5, 0xae, 0x8a, 0xe4, 0xa0, 0x1b, 0xe1,
	0x61, 0xe2, 0xd7, 0xff, 0x34, 0x7f, 0x07, 0x54, 0x8d, 0x53, 0x84, 0x3f, 0x27, 0x8b, 0x27, 0xd7,
	0xd3, 0x60, 0x18, 0x1b, 0x8c, 0x63, 0x83, 0x53, 0x63, 0x65, 0x3f, 0xfc, 0xba, 0x24, 0x92, 0x9e,
	0xd6, 0xf3, 0x00, 0xe8, 0x87, 0xa4, 0xe8, 0xb4, 0xfa, 0x56, 0x69, 0x41, 0xe7, 0x64, 0x71, 0x71,
	0xcd, 0x02, 0xfc, 0xc5, 0xc1, 0xc9, 0x97, 0xf4, 0x7e, 0x3c, 0xfb, 0x2f, 0x47, 0x5f, 0xc0, 0x9c,
	0x2c, 0xce, 0xa5, 0x83, 0xc9, 0xeb, 0xee, 0xd1, 0x53, 0xb8, 0x07, 0x93, 0x50, 0x86, 0xec, 0x8c,
	0x03, 0xb8, 0xb1, 0x92, 0xe1, 0xee, 0x86, 0x11, 0x4e, 0xc1, 0x59, 0xed, 0xa2, 0xf5, 0x86, 0x59,
	0xfc, 0x29, 0x50, 0xf5, 0x71, 0xbf, 0x59, 0x7f, 0x8a, 0x95, 0x64, 0x13, 0x7e, 0x0e, 0xfe, 0x76,
	0xb9, 0xbb, 0x41, 0x65, 0x23, 0xbc, 0x53, 0xcc, 0xe9, 0x81, 0xf7, 0xdb, 0x68, 0xa9, 0x98, 0xcb,
	0x7d, 0xb0, 0x57, 0x51, 0xb4, 0x65, 0x1e, 0xa2, 0xe1, 0xed, 0x26, 0x56, 0xcb, 0xdb, 0x3d, 0xf3,
	0x57, 0xec, 0xc7, 0x71, 0x46, 0x7e, 0x1e, 0x67, 0xe4, 0xf7, 0x71, 0x46, 0x1e, 0xfe, 0xcc, 0xce,
	0x52, 0x17, 0x37, 0xbf, 0xfd, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x19, 0xf1, 0x32, 0xe3, 0x37, 0x02,
	0x00, 0x00,
}
