// This file was AUTOMATICALLY GENERATED by dbg-import (smuggol) for github.com/robertkrimen/dbg

package otto

import (
	Dbg "github.com/google/cayley/Godeps/_workspace/src/github.com/robertkrimen/otto/dbg"
)

var dbg, dbgf = Dbg.New()
